# Generated by Django 5.0.6 on 2024-05-22 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='projects',
        ),
    ]
